version: "3.1"

services:

    db:
      image: postgres:11.5-alpine
      restart: always
      environment:
        POSTGRES_PASSWORD: ${DB_PASS}

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080

    server:
      restart: always
      build:
        context: ./server
        args:
          TIMEZONE: ${TIMEZONE}
      ports:
        - ${PORT}
      volumes:
        - ./server:/usr/src/app
      env_file: .env
      command: python GPS.py



